name: mmSupernaturals
main: me.matterz.supernaturals.SupernaturalsPlugin
version: 1.4.1
author: Matterz, edited by mmiillkkaa
commands:
  sn:
    description: Supernatural commands
    usage: /<command> - lists commands
permissions:
    supernatural.*:
        description: Gives access to every supernatural permission.
        children:
            supernatural.command.help: true
            supernatural.command.list: true
            supernatural.command.power: true
            supernatural.command.classes: true
            supernatural.command.killlist: true
            supernatural.player.shrineuse.vampire: true
            supernatural.player.shrineuse.priest: true
            supernatural.player.wolfbane: true
            supernatural.player.preventwaterdamage: true
            supernatural.player.preventsundamage: true
            supernatural.player.witchhuntersign: true
            supernatural.admin.infinitepower: true
            supernatural.admin.partial.curse: true
            supernatural.world.enabled: true
            supernatural.admin.command.adminhelp: true
            supernatural.admin.command.cure: true
            supernatural.admin.command.curse: true
            supernatural.admin.command.power: true
            supernatural.admin.command.reset: true
            supernatural.admin.command.reload: true
            supernatural.admin.command.save: true
            supernatural.admin.command.setchurch: true
            supernatural.admin.command.setbanish: true
    supernatural.command.*:
        description: Gives access to all player-commands
        children:
            supernatural.command.help: true
            supernatural.command.list: true
            supernatural.command.power: true
            supernatural.command.classes: true
            supernatural.command.killlist: true
    supernatural.player.*:
        description: Gives access to all player actions
        children:
            supernatural.player.shrineuse.vampire: true
            supernatural.player.shrineuse.priest: true
            supernatural.player.wolfbane: true
            supernatural.player.preventwaterdamage: true
            supernatural.player.preventsundamage: true
            supernatural.player.witchhuntersign: true
    supernatural.player.shrineuse.*:
        description: Gives access to all shrines
        children:
            supernatural.player.shrineuse.vampire: true
            supernatural.player.shrineuse.priest: true
    supernatural.admin.*:
        description: Gives access to all admin actions and commands
        children:
            supernatural.admin.infinitepower: true
            supernatural.admin.partial.curse: true
            supernatural.admin.command.adminhelp: true
            supernatural.admin.command.cure: true
            supernatural.admin.command.curse: true
            supernatural.admin.command.power: true
            supernatural.admin.command.reset: true
            supernatural.admin.command.reload: true
            supernatural.admin.command.save: true
            supernatural.admin.command.setchurch: true
            supernatural.admin.command.setbanish: true
    supernatural.command.help:
        default: true
    supernatural.command.list:
        default: true
    supernatural.command.power:
        default: true
    supernatural.command.classes:
        default: true
    supernatural.command.killlist:
        default: true
    supernatural.player.shrineuse.vampire:
        default: true
    supernatural.player.shrineuse.priest:
        default: true
    supernatural.player.wolfbane:
        default: true
    supernatural.player.preventwaterdamage:
        default: false
    supernatural.player.preventsundamage:
        default: false
    supernatural.player.witchhuntersign:
        default: true
    supernatural.admin.infinitepower:
        default: op
    supernatural.admin.partial.curse:
        default: op
    supernatural.world.enabled:
        default: true
    supernatural.admin.command.adminhelp:
        default: op
    supernatural.admin.command.cure:
        default: op
    supernatural.admin.command.curse:
        default: op
    supernatural.admin.command.power:
        default: op
    supernatural.admin.command.reset:
        default: op
    supernatural.admin.command.reload:
        default: op
    supernatural.admin.command.save:
        default: op
    supernatural.admin.command.setchurch:
        default: op
    supernatural.admin.command.setbanish:
        default: op